version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn
      - run: yarn ava
  lint:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn
      - run: yarn lint

workflows:
  version: 2
  test:
    jobs:
      - test
      - lint
