version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn
      - run: yarn ava
  lint:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo 'deploy'
      - run: exit 0
workflows:
  version: 2
  test:
    jobs:
      - test
      - lint
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
